language: java
install:
- wget https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
- tar -xzf geckodriver-v0.28.0-linux64.tar.gz -C bin
- export PATH=$(pwd)/bin:$PATH
addons:
  firefox: "49.0"
