language: java
services:
- mysql
addons:
  firefox: latest
before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS trabalhofinal;'
install:
- wget -N https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz -P ~/
- tar -xzf ~/geckodriver-v0.28.0-linux64.tar.gz -C ~/
- rm ~/geckodriver-v0.28.0-linux64.tar.gz
- sudo mv -f ~/geckodriver /usr/local/share
- sudo chmod +x /usr/local/share/geckodriver
- sudo ln -s /usr/local/share/geckodriver /usr/local/bin/geckodriver
script:
- timeout 3m mvn spring-boot:run | mvn verify


